driver/urls.py
from django.conf.urls import url
from django.urls import path
from driver import views

app_name = 'drivers'
urlpatterns = [
    path('checkin', views.checkin)
]

liban_ex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('', TemplateView.as_view(template_name="base.html")),
    path('order/', include('orders.urls')),
    path('driver/', include('driver.urls')),
    path('seller/', include('seller.urls')),
]

orders/urls.py
from django.conf.urls import url
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('entry', views.entry),
    path('assign', views.assign),
    path('update', views.update),
    path('search', views.search),
]

orders/models.py
from django.db import models
from seller.models import Seller
from driver.models import Driver
from areas.models import Zone, Location
from financials.models import Financial

# Create your models here.

class Order(models.Model):
    order_id = models.IntegerField(unique=True)
    date_received = models.DateTimeField()
    closed = models.DateTimeField(null=True, blank=True)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    amount_dollars = models.FloatField()
    amount_lebanese = models.FloatField()
    customer = models.CharField(max_length=100)
    address = models.TextField(max_length=500)
    phone_number = models.CharField(max_length=100)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, null=True, blank=True)
    zone = models.ForeignKey(Zone, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    financial_status = models.ForeignKey(Financial, on_delete=models.CASCADE)
    actual_usd = models.FloatField(null=True, blank=True)
    actual_lebanese = models.FloatField(null=True, blank=True)

    class Meta:
        ordering = ['order_id']

    def __str__(self):
        return str(self.order_id)


class OrderHistory(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    timestamp = models.DateTimeField()
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    financial_status = models.ForeignKey(Financial, on_delete=models.CASCADE)
    update = models.TextField(null=True, blank=True)

orders/forms.py
from django import forms
from orders.models import Order

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ('closed', 'actual_lebanese', 'actual_usd')

orders/views.py
from django.shortcuts import render, redirect
from orders.forms import *
from areas.models import Zone
from orders.models import Order
from driver.models import Driver
from seller.models import Seller
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from financials.models import Financial
from areas.models import Location
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def entry(request):
    form = OrderForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            messages.add_message(request, messages.SUCCESS, 'Order successfully created.')
            order = form.save()
            order.date_received = request.POST["date_received"] + " " + str(timezone.now().time())
            order.save()
    return render(request, 'orders/entry.html', {'form': form})

@login_required
def assign(request):
    zones = Zone.objects.all()
    drivers = Driver.objects.all()

    zone = request.GET.get("zone")
    if zone != "" and zone != None:
        zone = Zone.objects.get(zone=zone)
        orders = Order.objects.filter(zone=zone)

        page = request.GET.get('page', 1)
        paginator = Paginator(orders, 50)
        try:
            orders = paginator.page(page)
        except PageNotAnInteger:
            orders = paginator.page(1)
        except EmptyPage:
            orders = paginator.page(paginator.num_pages)

    else:
        orders = None

    if request.method == "POST":
        if request.POST.get("driver"):
            driver = Driver.objects.get(id=request.POST["driver"])
            orders = request.POST.getlist("selected_order")
            for order in orders:
                x = Order.objects.get(id=order)
                x.driver = driver
                x.save()
            messages.add_message(request, messages.SUCCESS, 'Your selected orders have been assigned to ' + str(driver))
            return redirect("/order/assign")

    return render(request, 'orders/assign.html', {"orders": orders, "zones": zones, "drivers": drivers, "selected": zone})

@login_required
def update(request):
    order = Order.objects.get(id=request.POST["order_id"])
    location = Location.objects.get(id=request.POST["location"])
    order.location = location
    order.actual_usd = float(request.POST["actual_dollars"])
    order.actual_lebanese = float(request.POST["actual_lebanese"])
    order.save()
    return HttpResponse('success')

@login_required
def search(request):
    seller = request.GET.get("seller", False)
    zone = request.GET.get("zone", False)
    location = request.GET.get("location", False)
    financial = request.GET.get("financial", False)

    orders = Order.objects.all()
    sellers = Seller.objects.all()
    zones = Zone.objects.all()
    locations = Location.objects.all()
    financials = Financial.objects.all()

    if request.method == "POST":
        number = request.POST["number"]
        order = Order.objects.filter(order_id=number)

        return render(request, "orders/search.html", {"orders": order, "sellers": sellers, "zones" : zones, "locations": locations, "financials": financials})

    else:
        if seller:
            seller = Seller.objects.get(id=seller)
            orders = orders.filter(seller=seller)

        selected_seller = seller

        if zone:
            zone = Zone.objects.get(id=zone)
            orders = orders.filter(zone=zone)

        selected_zone = zone

        if location:
            location = Location.objects.get(id=location)
            orders = orders.filter(location=location)

        selected_location = location

        if financial:
            financial = Financial.objects.get(id=financial)
            orders = orders.filter(financial_status=financial)

        selected_financial = financial

        return render(request, "orders/search.html", {"orders": orders, "sellers": sellers, "zones" : zones, "locations": locations, "financials": financials, "selected_seller": selected_seller, "selected_zone": selected_zone, "selected_location": selected_location, "selected_financial": selected_financial})

liban_ex/templates/orders/assign.html
{% extends 'base.html' %}

{% block content %}
{% for message in messages %}
<div class="alert alert-success text-center">
    <strong>{{ message }}</strong>
</div>
{% endfor %}

<style>

table {
    border-collapse: collapse;
    width: 50%;
    margin: 0 auto;
}

td, th {
    border: 1px solid black;
    text-align: center;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;

}

</style>

<div class="container-fluid text-center" style="margin-bottom: 100px;">
    <hr style="height:2px;border:none;color:#333;background-color:#333;" />
    <h3> Order assignment </h3><br>
    <form method="get">
        <select name="zone" class="form-control" required>
            <option value=""> Select zone to filter by </option>
            {% for zone in zones %}
            <option value="{{ zone.zone }}" {% if selected.zone == zone.zone %} selected {% endif %}> {{ zone }} </option>
            {% endfor %}
        </select><br>
        <input type="submit" class="btn btn-primary" value="Filter">
    </form>
    <hr style="height:2px;border:none;color:#333;background-color:#333;" />
    <h3>Assign selected orders to:</h3>
    <form method="post" name="form" id="form">
        {% csrf_token %}
        <select name="driver" class="form-control" required>
            <option value=""> Select driver </option>
            {% for driver in drivers %}
            <option value="{{ driver.id }}"> {{ driver }} </option>
            {% endfor %}
        </select><br>
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
    <hr style="height:2px;border:none;color:#333;background-color:#333;" />

    {% if orders %}
    <br>
    <div class='text-center'>
        <table style="width: 100%;">
            <tr>
                <th> Order id </th>
                <th> Date received </th>
                <th> Closed date </th>
                <th> Seller </th>
                <th> Amount in dollars </th>
                <th> Amount in lebanese </th>
                <th> Customer </th>
                <th> Address </th>
                <th> Phone number </th>
                <th> Driver </th>
                <th> Zone </th>
                <th> Location </th>
                <th> Financial status </th>
                <th> Actual amount </th>
            </tr>
            {% for order in orders %}
            <tr>
                <th> {{ order.order_id }} </th>
                <th> {{ order.date_received }} </th>
                <th> {{ order.closed }} </th>
                <th> {{ order.seller }} </th>
                <th> {{ order.amount_dollars }} </th>
                <th> {{ order.amount_lebanese }} </th>
                <th> {{ order.customer }} </th>
                <th> {{ order.address }} </th>
                <th> {{ order.phone_number }} </th>
                <th> {{ order.driver }} </th>
                <th> {{ order.zone }} </th>
                <th> {{ order.location }} </th>
                <th> {{ order.financial_status }} </th>
                <th> {{ order.actual_amount }} </th>
                <th> <input type="checkbox" name="selected_order" form="form" value="{{ order.id }}" style="width: 15px; height: 15px;"> </th>
            </tr>
            {% endfor %}
        </table>

        {% if orders.has_other_pages %}
          <ul class="pagination">
            {% if orders.has_previous %}
              <li><a href="{{ request.build_absolute_uri }}&page={{ orders.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in orders.paginator.page_range %}
              {% if orders.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="{{ request.build_absolute_uri }}&page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if orders.has_next %}
              <li><a href="{{ request.build_absolute_uri }}&page={{ orders.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}

    </div>
    {% endif %}

</div>

{% endblock %}

liban_ex/templates/orders/entry.html
{% extends 'base.html' %}

{% block content %}
{% for message in messages %}
<div class="alert alert-success text-center">
    <strong>{{ message }}</strong>
</div>
{% endfor %}
<br>
<div class="container" style="margin-bottom: 100px;">
    <h3 class="text-center"> Order Entry </h3>
    <form method="post">
        {% csrf_token %}
        <div>
            <br>
            {% for field in form %}
            {% if field.label != "Address" %}
                <span>{{ field.label }}:</span>
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
                <span class="">{{ field }}</span>{% if forloop.counter|divisibleby:4 %}<br><br>{% endif %}
            {% endif %}
            {% endfor %}
            {{ form.address.label }}:<br> {{ form.address }}<br>
        </div>
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
</div>
{% endblock %}

{% block footer_js %}
<script>
    $("#id_amount_dollars").change(function(){
        var x = parseFloat($("#id_amount_dollars").val()) * 1500;
        $("#id_amount_lebanese").val(x);
    });
    $("#id_amount_lebanese").change(function(){
        var x = parseFloat($("#id_amount_lebanese").val()) / 1500;
        $("#id_amount_dollars").val(x);
    });

    var today = new Date();
    var dd = today.getDate();
    var mm = today.getMonth()+1; //January is 0!

    var yyyy = today.getFullYear();
    if(dd<10){
        dd='0'+dd;
    }
    if(mm<10){
        mm='0'+mm;
    }
    var today = yyyy+'-'+mm+'-'+dd;
    document.getElementById("id_date_received").value = today;

</script>
{% endblock %}

liban_ex/templates/orders/search.html
{% extends 'base.html' %}

{% block content %}
{% for message in messages %}
<div class="alert alert-success text-center">
    <strong>{{ message }}</strong>
</div>
{% endfor %}

<style>

.form-control {
    width: auto;
    display: inline;
}

table {
    border-collapse: collapse;
    width: 50%;
    margin: 0 auto;
}

td, th {
    border: 1px solid black;
    text-align: center;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;

}

</style>

<br>
<div class="container" style="margin-bottom: 100px;">
    <h3 class="text-center"> Order Search </h3>
    <br>

    <h4> Search for order number: </h4>
    <form method="post">
        {% csrf_token %}
        <input type="text" required name="number" placeholder="Order number" class="form-control">
        <input type="submit" class="btn btn-primary" value="Submit">
    </form><br><br>

    <h4> Filter by: </h4>
    <form method="get">
        <select name="seller" class="form-control">
            <option value=""> Seller </option>
            {% for seller in sellers %}
            <option value="{{ seller.id }}" {% if selected_seller == seller %} selected {% endif %}> {{ seller }} </option>
            {% endfor %}
        </select>
        <select name="zone" class="form-control">
            <option value=""> Zone </option>
            {% for zone in zones %}
            <option value="{{ zone.id }}" {% if selected_zone == zone %} selected {% endif %}> {{ zone }} </option>
            {% endfor %}
        </select>
        <select name="location" class="form-control">
            <option value=""> Location </option>
            {% for location in locations %}
            <option value="{{ location.id }}" {% if selected_location == location %} selected {% endif %}> {{ location }} </option>
            {% endfor %}
        </select>
        <select name="financial" class="form-control">
            <option value=""> Financial Status </option>
            {% for financial in financials %}
            <option value="{{ financial.id }}" {% if selected_financial == financial %} selected {% endif %}> {{ financial }} </option>
            {% endfor %}
        </select>
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
    {% if orders %}
    <br>
    <br>
    <div class='text-center'>
        <table style="width: 100%;">
            <tr>
                <th> Order id </th>
                <th> Date received </th>
                <th> Closed date </th>
                <th> Seller </th>
                <th> Amount in dollars </th>
                <th> Amount in lebanese </th>
                <th> Driver </th>
                <th> Zone </th>
                <th> Location </th>
                <th> Financial status </th>
                <th> Actual amount USD</th>
                <th> Actual amount LBP</th>
            </tr>
            {% for order in orders %}
            <tr>
                <th> {{ order.order_id }} </th>
                <th> {{ order.date_received.date }} </th>
                <th> {{ order.closed }} </th>
                <th> {{ order.seller }} </th>
                <th> {{ order.amount_dollars }} </th>
                <th> {{ order.amount_lebanese }} </th>
                <th> {{ order.driver }} </th>
                <th> {{ order.zone }} </th>
                <th> {{ order.location }} </th>
                <th> {{ order.financial_status }} </th>
                <th> {{ order.actual_usd }} </th>
                <th> {{ order.actual_lebanese }} </th>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    <br>
    <h3> No results found. </h3>
    {% endif %}
</div>

{% endblock %}

{% block footer_js %}
{% endblock %}